# Generated by Django 2.1.5 on 2019-03-06 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
